In [1]:
(5,7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [3]:
(5,)

(5,)

In [4]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [7]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [9]:
import numpy as np

l = [[1,2,3],[2,3,4]]
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype

(2, (2, 3), 6, dtype('int64'))

In [11]:
import numpy as np
np.random.randn(10,5)

array([[ 0.53841756, -0.18513258,  1.06703326, -0.31235517, -0.35922857],
       [-0.00455612,  0.94633116,  0.59319705, -1.67292502, -1.0608963 ],
       [ 0.3996462 ,  0.71616968,  0.37567978, -1.74442522, -1.19109472],
       [ 0.23473729,  1.02400258, -0.19084743,  1.22253673,  0.02142558],
       [-0.90119916,  0.42296921, -0.21415737,  0.55325491,  0.27655133],
       [-0.79318464,  0.23786029,  0.29266534,  0.9600372 , -0.88811432],
       [ 0.80267664,  0.70969849,  0.60922175,  2.08292097,  1.45541184],
       [ 1.58095265,  1.31609941,  0.13813282,  0.09600803, -0.02325212],
       [-0.23073038,  0.54991508,  1.61118153,  0.67052036,  0.54822733],
       [-0.32922404,  0.76739867,  1.09355738,  0.75036972, -2.4697411 ]])

In [17]:
#50個學生,每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 89,  78,  52,  59,  87],
       [ 64,  97,  87,  98,  68],
       [ 56,  69,  86,  85,  92],
       [ 78,  53,  80,  85,  54],
       [ 79,  58,  92,  71,  97],
       [ 60,  91,  76,  81,  99],
       [ 86,  70,  71,  99,  97],
       [ 96,  62,  83,  75,  81],
       [ 78,  74,  52,  58,  71],
       [ 58,  77,  74,  70,  70],
       [ 78,  96,  99,  77,  61],
       [ 79,  92,  78,  84,  65],
       [ 72,  98,  67,  91,  79],
       [ 97,  57,  78,  65,  51],
       [ 64,  94,  54,  73,  73],
       [ 56,  76,  81,  87,  61],
       [ 62,  87,  56,  78,  74],
       [100,  69, 100,  73,  86],
       [ 86,  76,  65,  85,  72],
       [ 99,  67,  90,  58,  82],
       [ 56,  62,  68,  82,  52],
       [ 67,  66,  94,  83,  64],
       [ 66,  90,  79,  56,  67],
       [ 51,  50,  52,  80,  50],
       [ 61,  80,  51,  96,  77],
       [ 70,  70,  82,  59,  85],
       [ 59,  81,  52,  91,  86],
       [ 65,  82,  89,  89,  81],
       [ 52,  81,  95,  90,  59],
       [ 94,  