In [1]:
(5,7)

(5, 7)

In [2]:
5, 7

(5, 7)

In [3]:
(5,)

(5,)

In [4]:
list_a = [1, 3, 5, 7, 9]
list_b = [3, 5, 6, 7, 9]
list_a + list_b

[1, 3, 5, 7, 9, 3, 5, 6, 7, 9]

In [7]:
import numpy as np
array_a = np.array([1, 3, 5, 7, 9])
array_b = np.array([3, 5, 6, 7, 9])
type(array_a)
array_a + array_b

array([ 4,  8, 11, 14, 18])

In [9]:
import numpy as np

l = [[1,2,3],[2,3,4]]
array = np.array(l)
array.ndim, array.shape, array.size, array.dtype

(2, (2, 3), 6, dtype('int64'))

In [11]:
import numpy as np
np.random.randn(10,5)

array([[ 0.53841756, -0.18513258,  1.06703326, -0.31235517, -0.35922857],
       [-0.00455612,  0.94633116,  0.59319705, -1.67292502, -1.0608963 ],
       [ 0.3996462 ,  0.71616968,  0.37567978, -1.74442522, -1.19109472],
       [ 0.23473729,  1.02400258, -0.19084743,  1.22253673,  0.02142558],
       [-0.90119916,  0.42296921, -0.21415737,  0.55325491,  0.27655133],
       [-0.79318464,  0.23786029,  0.29266534,  0.9600372 , -0.88811432],
       [ 0.80267664,  0.70969849,  0.60922175,  2.08292097,  1.45541184],
       [ 1.58095265,  1.31609941,  0.13813282,  0.09600803, -0.02325212],
       [-0.23073038,  0.54991508,  1.61118153,  0.67052036,  0.54822733],
       [-0.32922404,  0.76739867,  1.09355738,  0.75036972, -2.4697411 ]])

In [18]:
#50個學生,每個學生有5個分數(50-100)
scores = np.random.randint(50,101,size=(50,5))
scores

array([[ 60,  78,  64, 100,  68],
       [ 82,  57,  58,  53,  78],
       [ 88,  75,  50,  59,  62],
       [ 75,  50,  73,  66,  64],
       [ 96,  76,  74,  98,  89],
       [ 78,  63,  98,  65,  97],
       [ 58,  96,  99,  68,  62],
       [ 53,  79,  54,  53,  51],
       [ 59,  79,  81,  57,  65],
       [ 53,  99,  81,  97,  60],
       [100,  64,  56,  93,  70],
       [ 85, 100,  68,  70,  53],
       [ 52,  99,  71,  72,  67],
       [ 53,  83,  85,  73,  80],
       [ 72,  77,  89,  80,  59],
       [ 88,  94,  53,  65,  83],
       [ 99,  74,  85,  99,  67],
       [ 70,  60,  82,  64,  71],
       [ 61,  92,  90,  90,  88],
       [ 73,  51,  82,  68,  78],
       [ 74,  81,  77,  73,  70],
       [ 61,  85,  73,  92,  55],
       [ 57,  50,  78,  80,  71],
       [ 75,  85,  77,  85,  66],
       [ 97,  62,  81,  78,  70],
       [ 99,  67,  62,  54,  58],
       [ 70,  78,  51,  62,  76],
       [ 52,  93,  63,  96,  96],
       [ 62,  50,  60,  77,  97],
       [ 87,  

In [22]:
#第一個學生
scores[0,:]
#前5個學生
scores[:5,:]
#最後5個學生
scores[-5:,:]

array([[77, 82, 51, 73, 54],
       [71, 96, 54, 79, 90],
       [98, 57, 81, 79, 73],
       [79, 57, 60, 51, 90],
       [73, 92, 92, 59, 93]])

In [23]:
#全班第1科的分數
scores[:,0]

array([ 60,  82,  88,  75,  96,  78,  58,  53,  59,  53, 100,  85,  52,
        53,  72,  88,  99,  70,  61,  73,  74,  61,  57,  75,  97,  99,
        70,  52,  62,  87,  80,  72,  93,  83,  75,  93,  82,  60,  72,
        96,  82,  64,  78,  93,  54,  77,  71,  98,  79,  73])

In [24]:
#全班第2科的分數
scores[:,1]

array([ 78,  57,  75,  50,  76,  63,  96,  79,  79,  99,  64, 100,  99,
        83,  77,  94,  74,  60,  92,  51,  81,  85,  50,  85,  62,  67,
        78,  93,  50,  52,  91,  54,  72,  50,  72,  80,  64,  95,  62,
        50,  90,  87,  93,  69, 100,  82,  96,  57,  57,  92])

In [26]:
#每位學生的總分
total = scores[:,0] + scores[:,1] + scores[:,2] + scores[:,3] + scores[:,4] 
total

array([370, 328, 334, 328, 433, 401, 383, 290, 341, 390, 383, 376, 361,
       374, 377, 383, 424, 347, 421, 352, 375, 366, 336, 388, 388, 340,
       337, 400, 346, 363, 366, 313, 361, 356, 389, 341, 387, 421, 327,
       415, 339, 395, 350, 351, 355, 337, 390, 388, 337, 409])

In [27]:
#使用統計的方法
#每個學生總分
np.sum(scores,axis=1)

array([370, 328, 334, 328, 433, 401, 383, 290, 341, 390, 383, 376, 361,
       374, 377, 383, 424, 347, 421, 352, 375, 366, 336, 388, 388, 340,
       337, 400, 346, 363, 366, 313, 361, 356, 389, 341, 387, 421, 327,
       415, 339, 395, 350, 351, 355, 337, 390, 388, 337, 409])

In [28]:
#每個學生平均
np.mean(scores,axis=1)

array([74. , 65.6, 66.8, 65.6, 86.6, 80.2, 76.6, 58. , 68.2, 78. , 76.6,
       75.2, 72.2, 74.8, 75.4, 76.6, 84.8, 69.4, 84.2, 70.4, 75. , 73.2,
       67.2, 77.6, 77.6, 68. , 67.4, 80. , 69.2, 72.6, 73.2, 62.6, 72.2,
       71.2, 77.8, 68.2, 77.4, 84.2, 65.4, 83. , 67.8, 79. , 70. , 70.2,
       71. , 67.4, 78. , 77.6, 67.4, 81.8])